/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package program.aritmatika;

/**
 *
 * @author ASUS
 */
public class programaritmatikaa extends javax.swing.JFrame {
    String jns="";
    int jmlh;
    /**
     * Creates new form programaritmatikaa
     */
    public programaritmatikaa() {
        initComponents();
        jns = null;
        panel.setVisible(false);
        bil1.setVisible(false);
                bil2.setVisible(false);
                bil3.setVisible(false);
                bil4.setVisible(false);
                b1.setVisible(false);
                b2.setVisible(false);
                b3.setVisible(false);
                b4.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        panel = new javax.swing.JPanel();
        bil1 = new javax.swing.JTextField();
        bil2 = new javax.swing.JTextField();
        bil3 = new javax.swing.JTextField();
        bil4 = new javax.swing.JTextField();
        b4 = new javax.swing.JLabel();
        b3 = new javax.swing.JLabel();
        b2 = new javax.swing.JLabel();
        ket = new javax.swing.JLabel();
        jumlah = new javax.swing.JComboBox<>();
        b1 = new javax.swing.JLabel();
        hitung = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        hasil = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jenis = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel4.setFont(new java.awt.Font("Britannic Bold", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 102));
        jLabel4.setText("JENIS ARITMATIKA");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 100, 150, 30);

        jPanel3.setBackground(new java.awt.Color(255, 204, 204));
        jPanel3.setLayout(null);

        panel.setBackground(new java.awt.Color(255, 0, 102));
        panel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "OPERASI", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 24), new java.awt.Color(255, 204, 204))); // NOI18N
        panel.setLayout(null);

        bil1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        bil1.setForeground(new java.awt.Color(255, 0, 102));
        bil1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bil1ActionPerformed(evt);
            }
        });
        panel.add(bil1);
        bil1.setBounds(180, 140, 460, 40);

        bil2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        bil2.setForeground(new java.awt.Color(255, 0, 102));
        panel.add(bil2);
        bil2.setBounds(180, 190, 460, 40);

        bil3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        bil3.setForeground(new java.awt.Color(255, 0, 102));
        panel.add(bil3);
        bil3.setBounds(180, 240, 460, 40);

        bil4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        bil4.setForeground(new java.awt.Color(255, 0, 102));
        panel.add(bil4);
        bil4.setBounds(180, 290, 460, 40);

        b4.setFont(new java.awt.Font("Britannic Bold", 0, 16)); // NOI18N
        b4.setForeground(new java.awt.Color(255, 204, 204));
        b4.setText("BILANGAN 4");
        panel.add(b4);
        b4.setBounds(20, 300, 130, 20);

        b3.setFont(new java.awt.Font("Britannic Bold", 0, 16)); // NOI18N
        b3.setForeground(new java.awt.Color(255, 204, 204));
        b3.setText("BILANGAN 3");
        panel.add(b3);
        b3.setBounds(20, 250, 130, 20);

        b2.setFont(new java.awt.Font("Britannic Bold", 0, 16)); // NOI18N
        b2.setForeground(new java.awt.Color(255, 204, 204));
        b2.setText("BILANGAN 2");
        panel.add(b2);
        b2.setBounds(20, 200, 130, 20);

        ket.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        ket.setForeground(new java.awt.Color(255, 204, 204));
        panel.add(ket);
        ket.setBounds(270, 30, 250, 40);

        jumlah.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jumlah.setForeground(new java.awt.Color(255, 0, 102));
        jumlah.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--PILIH--", "2", "3", "4" }));
        jumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jumlahActionPerformed(evt);
            }
        });
        panel.add(jumlah);
        jumlah.setBounds(180, 80, 460, 50);

        b1.setFont(new java.awt.Font("Britannic Bold", 0, 16)); // NOI18N
        b1.setForeground(new java.awt.Color(255, 204, 204));
        b1.setText("BILANGAN 1");
        panel.add(b1);
        b1.setBounds(20, 150, 130, 20);

        hitung.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        hitung.setForeground(new java.awt.Color(255, 0, 102));
        hitung.setText("HITUNG");
        hitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitungActionPerformed(evt);
            }
        });
        panel.add(hitung);
        hitung.setBounds(360, 340, 110, 30);

        jLabel10.setFont(new java.awt.Font("Britannic Bold", 0, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 204, 204));
        jLabel10.setText("JUMLAH BILANGAN");
        panel.add(jLabel10);
        jLabel10.setBounds(20, 100, 150, 20);

        hasil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hasilActionPerformed(evt);
            }
        });
        panel.add(hasil);
        hasil.setBounds(180, 380, 460, 120);

        jPanel3.add(panel);
        panel.setBounds(0, 160, 650, 510);

        jLabel3.setFont(new java.awt.Font("Futura Bk BT", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 102));
        jLabel3.setText("PROGAM ARITMATIKA");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(140, 0, 360, 80);

        jenis.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jenis.setForeground(new java.awt.Color(255, 0, 102));
        jenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--PILIH--", "PERKALIAN", "PEMBAGIAN", "PENGURANGAN", "PENJUMLAHAN" }));
        jenis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jenisActionPerformed(evt);
            }
        });
        jPanel3.add(jenis);
        jenis.setBounds(180, 90, 460, 50);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 0, 670, 690);

        setBounds(0, 0, 680, 723);
    }// </editor-fold>//GEN-END:initComponents

    private void jenisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jenisActionPerformed
        // TODO add your handling code here:
        setJenis(); 
    }//GEN-LAST:event_jenisActionPerformed
        public void setJenis(){
            if( jenis.getSelectedItem().equals("PENJUMLAHAN")){
                jns = "PENJUMLAHAN";
                ket.setText("PENJUMLAHAN");
                panel.setVisible(true);
                jumlah.setEnabled(true);
        }
            else if( jenis.getSelectedItem().equals("PENGURANGAN")){
                jns = "PENGURANGAN";
                ket.setText("PENGURANGAN");
                panel.setVisible(true);
                jumlah.setEnabled(true);
        }
            else if( jenis.getSelectedItem().equals("PERKALIAN")){
                jns = "PERKALIAN";
                ket.setText("PERKALIAN");
                panel.setVisible(true);
                jumlah.setEnabled(true);
        }
            else if( jenis.getSelectedItem().equals("PEMBAGIAN")){
                jns = "PEMBAGIAN";
                ket.setText("PEMBAGIAN");
                panel.setVisible(true);
                jumlah.setEnabled(true);
        }
            else{
                jns = null;
                panel.setVisible(false);
        }
    }
    
    private void bil1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bil1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bil1ActionPerformed

    private void hitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitungActionPerformed
        // TODO add your handling code here:
        Double hsl;
        Double a1,a2,a3,a4;
        
        a1 = Double.parseDouble(bil1.getText().toString());
        a2 = Double.parseDouble(bil2.getText().toString());
        
        if(jns.equals("PENJUMLAHAN")){
            if(jmlh == 2){
                hsl = a1 + a2;
                hasil.setText(""+ a1 + " + " + a2 + " = " + hsl);
            }
            if(jmlh == 3){
                a3 = Double.parseDouble(bil3.getText().toString());
                hsl = a1 + a2 + a3;
                hasil.setText(""+ a1 + " + " + a2 + " + " + a3 + " = " + hsl);
            }
            if(jmlh == 4){
                a3 = Double.parseDouble(bil3.getText().toString());
                a4 = Double.parseDouble(bil4.getText().toString());
                hsl = a1 + a2 + a3 + a4;
                hasil.setText(""+ a1 + " + " + a2 + " + " + a3 + "+ " + a4 + " = " + hsl);
            }
        }
        else if(jns.equals("PENGURANGAN")){
            if(jmlh == 2){
                hsl = a1 - a2;
                hasil.setText(""+ a1 + " - " + a2 + " = " + hsl);
            }
            if(jmlh == 3){
                a3 = Double.parseDouble(bil3.getText().toString());
                hsl = a1 - a2 - a3;
                hasil.setText(""+ a1 + " - " + a2 + " - " + a3 + " = " + hsl);
            }
            if(jmlh == 4){
                a3 = Double.parseDouble(bil3.getText().toString());
                a4 = Double.parseDouble(bil4.getText().toString());
                hsl = a1 - a2 - a3 - a4;
                hasil.setText(""+ a1 + " - " + a2 + " - " + a3 + " - " + a4 + " = " + hsl);
            }
        }
        else if(jns.equals("PERKALIAN")){
            if(jmlh == 2){
                hsl = a1 * a2;
                hasil.setText(""+ a1 + " x " + a2 + " = " + hsl);
            }
            if(jmlh == 3){
                a3 = Double.parseDouble(bil3.getText().toString());
                hsl = a1 * a2 * a3;
                hasil.setText(""+ a1 + " x " + a2 + " x " + a3 + " = " + hsl);
            }
            if(jmlh == 4){
                a3 = Double.parseDouble(bil3.getText().toString());
                a4 = Double.parseDouble(bil4.getText().toString());
                hsl = a1 * a2 * a3 * a4;
                hasil.setText(""+ a1 + " x " + a2 + " x " + a3 + " x " + a4 + " = " + hsl);
            }
        }
        else if(jns.equals("PEMBAGIAN")){
            if(jmlh == 2){
                hsl = a1 / a2;
                hasil.setText(""+ a1 + " / " + a2 + " = " + hsl);
            }
            if(jmlh == 3){
                a3 = Double.parseDouble(bil3.getText().toString());
                hsl = a1 / a2 / a3;
                hasil.setText(""+ a1 + " / " + a2 + " / " + a3 + " = " + hsl);
            }
            if(jmlh == 4){
                a3 = Double.parseDouble(bil3.getText().toString());
                a4 = Double.parseDouble(bil4.getText().toString());
                hsl = a1 / a2 / a3 / a4;
                hasil.setText(""+ a1 + " / " + a2 + " / " + a3 + " / " + a4 + " = " + hsl);
            }
        }
    }//GEN-LAST:event_hitungActionPerformed

    private void hasilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hasilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hasilActionPerformed

    private void jumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jumlahActionPerformed
        // TODO add your handling code here:
        getJumlah();
    }//GEN-LAST:event_jumlahActionPerformed

    public void getJumlah(){
        if( jumlah.getSelectedItem().equals("2")){
                bil1.setVisible(true);
                bil2.setVisible(true);
                bil3.setVisible(false);
                bil4.setVisible(false);
                b1.setVisible(true);
                b2.setVisible(true);
                b3.setVisible(false);
                b4.setVisible(false);
                jmlh = 2;
        }
        else if( jumlah.getSelectedItem().equals("3")){
                bil1.setVisible(true);
                bil2.setVisible(true);
                bil3.setVisible(true);
                bil4.setVisible(false);
                b1.setVisible(true);
                b2.setVisible(true);
                b3.setVisible(true);
                b4.setVisible(false);
                jmlh = 3;
        }
        else if( jumlah.getSelectedItem().equals("4")){
                bil1.setVisible(true);
                bil2.setVisible(true);
                bil3.setVisible(true);
                bil4.setVisible(true);
                b1.setVisible(true);
                b2.setVisible(true);
                b3.setVisible(true);
                b4.setVisible(true);
                jmlh = 4;
        }
        else{
                bil1.setVisible(false);
                bil2.setVisible(false);
                bil3.setVisible(false);
                bil4.setVisible(false);
                b1.setVisible(false);
                b2.setVisible(false);
                b3.setVisible(false);
                b4.setVisible(false);
                
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(programaritmatikaa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(programaritmatikaa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(programaritmatikaa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(programaritmatikaa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new programaritmatikaa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel b1;
    private javax.swing.JLabel b2;
    private javax.swing.JLabel b3;
    private javax.swing.JLabel b4;
    private javax.swing.JTextField bil1;
    private javax.swing.JTextField bil2;
    private javax.swing.JTextField bil3;
    private javax.swing.JTextField bil4;
    private javax.swing.JTextField hasil;
    private javax.swing.JButton hitung;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JComboBox<String> jenis;
    private javax.swing.JComboBox<String> jumlah;
    private javax.swing.JLabel ket;
    private javax.swing.JPanel panel;
    // End of variables declaration//GEN-END:variables
}
